version: '3.8'
services:
  envoy:
    container_name: envoy
    image: quickfeed/envoy
    build:
      context: ./ci/docker/envoy
      dockerfile: ./Dockerfile
      args:
        - ENVOY_CONFIG=${ENVOY_CONFIG}
        - DOMAIN=${DOMAIN}
    ports:
      - "80:80"
      - "443:443"
      # - "9901:9901" # envoy admin endpoint.
    networks:
      - quickfeed_net

  quickfeed:
    container_name: quickfeed
    image: quickfeed/quickfeed
    build:
      context: ./
      dockerfile: ./ci/docker/quickfeed/Dockerfile
      args:
        - GRPC_PORT=${GRPC_PORT}
        - HTTP_PORT=${HTTP_PORT}
    links:
      - envoy
    # Uncomment to expose quickfeed ports for debugging on the host machine.
    # ports:
    #   - "8081:8081"
    #   - "9090:9090"
    networks:
      - quickfeed_net

networks:
  quickfeed_net:
    ipam:
      config:
      - subnet: 172.20.0.0/16
