name: Test Coverage
on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.19]

    steps:
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache: true

      - name: Generate coverage report
        run: DOCKER_TESTS=1 go test -v -coverprofile=profile.cov -covermode=atomic ./...

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: profile.cov
          flag-name: Go-${{ matrix.go-version }}
          parallel: true

      - name: Upload coverage report to codecov.io
        uses: codecov/codecov-action@v2
        with:
          files: ./profile.cov
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

  # notifies that all test jobs are finished.
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
